// Re-export from shared package — single source of truth
export {
  XP_TASK_COMPLETE,
  XP_SUBSKILL_COMPLETE,
  XP_SKILL_ARCHIVE,
  XP_CHECK_IN_SUBMITTED,
  XP_CHECK_IN_YES_BONUS,
  XP_SHARED_STREAK_DAY,
  XP_SHARED_STREAK_7_DAY,
  XP_SHARED_STREAK_30_DAY,
  XP_DAMAGE_MISS,
  SHARED_STREAK_MILESTONES,
  MAX_ACTIVE_PARTNERS,
  LEVEL_THRESHOLDS,
  MAX_LEVEL,
  calculateLevel,
  getLevelProgress,
  LEVEL_NAMES,
  getLevelName,
} from '@willdo/shared';
