/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTodolistRouteImport } from './routes/app/todolist'
import { Route as AppSkillsRouteImport } from './routes/app/skills'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppReflectionsRouteImport } from './routes/app/reflections'
import { Route as AppHelpRouteImport } from './routes/app/help'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppSkillsNewRouteImport } from './routes/app/skills_.new'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as AppSkillsIdPlannerRouteImport } from './routes/app/skills_.$id.planner'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTodolistRoute = AppTodolistRouteImport.update({
  id: '/todolist',
  path: '/todolist',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReflectionsRoute = AppReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsNewRoute = AppSkillsNewRouteImport.update({
  id: '/skills_/new',
  path: '/skills/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSkillsIdPlannerRoute = AppSkillsIdPlannerRouteImport.update({
  id: '/skills_/$id/planner',
  path: '/skills/$id/planner',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/help': typeof AppHelpRoute
  '/app/reflections': typeof AppReflectionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/todolist': typeof AppTodolistRoute
  '/app/': typeof AppIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/skills/new': typeof AppSkillsNewRoute
  '/app/skills/$id/planner': typeof AppSkillsIdPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/help': typeof AppHelpRoute
  '/app/reflections': typeof AppReflectionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/todolist': typeof AppTodolistRoute
  '/app': typeof AppIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/skills/new': typeof AppSkillsNewRoute
  '/app/skills/$id/planner': typeof AppSkillsIdPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/help': typeof AppHelpRoute
  '/app/reflections': typeof AppReflectionsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/todolist': typeof AppTodolistRoute
  '/app/': typeof AppIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/skills_/new': typeof AppSkillsNewRoute
  '/app/skills_/$id/planner': typeof AppSkillsIdPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/app/help'
    | '/app/reflections'
    | '/app/settings'
    | '/app/skills'
    | '/app/todolist'
    | '/app/'
    | '/api/trpc/$'
    | '/app/skills/new'
    | '/app/skills/$id/planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/dashboard'
    | '/app/help'
    | '/app/reflections'
    | '/app/settings'
    | '/app/skills'
    | '/app/todolist'
    | '/app'
    | '/api/trpc/$'
    | '/app/skills/new'
    | '/app/skills/$id/planner'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/app/help'
    | '/app/reflections'
    | '/app/settings'
    | '/app/skills'
    | '/app/todolist'
    | '/app/'
    | '/api/trpc/$'
    | '/app/skills_/new'
    | '/app/skills_/$id/planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/todolist': {
      id: '/app/todolist'
      path: '/todolist'
      fullPath: '/app/todolist'
      preLoaderRoute: typeof AppTodolistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skills': {
      id: '/app/skills'
      path: '/skills'
      fullPath: '/app/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reflections': {
      id: '/app/reflections'
      path: '/reflections'
      fullPath: '/app/reflections'
      preLoaderRoute: typeof AppReflectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skills_/new': {
      id: '/app/skills_/new'
      path: '/skills/new'
      fullPath: '/app/skills/new'
      preLoaderRoute: typeof AppSkillsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/skills_/$id/planner': {
      id: '/app/skills_/$id/planner'
      path: '/skills/$id/planner'
      fullPath: '/app/skills/$id/planner'
      preLoaderRoute: typeof AppSkillsIdPlannerRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppHelpRoute: typeof AppHelpRoute
  AppReflectionsRoute: typeof AppReflectionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppTodolistRoute: typeof AppTodolistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSkillsNewRoute: typeof AppSkillsNewRoute
  AppSkillsIdPlannerRoute: typeof AppSkillsIdPlannerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppHelpRoute: AppHelpRoute,
  AppReflectionsRoute: AppReflectionsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppTodolistRoute: AppTodolistRoute,
  AppIndexRoute: AppIndexRoute,
  AppSkillsNewRoute: AppSkillsNewRoute,
  AppSkillsIdPlannerRoute: AppSkillsIdPlannerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
